blank_issues_enabled: true
contact_links:
  - name: Issue
    about: Issue template
    url: https://github.com/yoshida0261/issues/new?template=feature_request.md&projects=https://github.com/users/yoshida0261/projects/1&labels=enhancement
