blank_issues_enabled: true
contact_links:
  - name: Issue
    about: Issue template
    url: https://github.com/yoshida0261/issues/new?template=feature_request.md&projects=yoshida0261/1&labels=enhancement
