measure-build-time:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Prefetch Gradle Dependencies
      run: ./gradlew --no-daemon assembleDebug
    - name: Run gradle-profiler
      run: |
        curl -s "https://get.sdkman.io" | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install gradleprofiler 0.18.0
        gradle-profiler --benchmark --scenario-file .github/performance.scenario build --gradle-user-home $HOME/.gradle
    - uses: actions/upload-artifact@v2
      name: Archive
      with:
        name: result
        path: profile-out
