name: Add bugs to bugs project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/orgs/yoshida0261/projects/1
          github-token: ${{ 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 }}
          labeled: bug, needs-triage
          label-operator: OR
